//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Method635.App.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Method635.App.Forms.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brainstorming Finding.
        /// </summary>
        internal static string AddFinding {
            get {
                return ResourceManager.GetString("AddFinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brainstorming Team.
        /// </summary>
        internal static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Sheet.
        /// </summary>
        internal static string AddToSheet {
            get {
                return ResourceManager.GetString("AddToSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Team, placing call to join it...
        /// </summary>
        internal static string BottomOverlayText {
            get {
                return ResourceManager.GetString("BottomOverlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brainstorming.
        /// </summary>
        internal static string Brainstorming {
            get {
                return ResourceManager.GetString("Brainstorming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description of the topic the brainstorming is about..
        /// </summary>
        internal static string BrainstormingDescription {
            get {
                return ResourceManager.GetString("BrainstormingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brainstorming Findings.
        /// </summary>
        internal static string BrainstormingFindings {
            get {
                return ResourceManager.GetString("BrainstormingFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brainstorming Title.
        /// </summary>
        internal static string BrainstormingTitle {
            get {
                return ResourceManager.GetString("BrainstormingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a pattern from a category.
        /// </summary>
        internal static string ChoosePatternTitle {
            get {
                return ResourceManager.GetString("ChoosePatternTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the icon to start Brainstorming..
        /// </summary>
        internal static string ClickToStartBrainstorming {
            get {
                return ResourceManager.GetString("ClickToStartBrainstorming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export has been copied to your clipboard as markdown..
        /// </summary>
        internal static string CopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("CopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported to Clipboard.
        /// </summary>
        internal static string CopiedToClipboardTitle {
            get {
                return ResourceManager.GetString("CopiedToClipboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Finding.
        /// </summary>
        internal static string CreateFinding {
            get {
                return ResourceManager.GetString("CreateFinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Account.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Team.
        /// </summary>
        internal static string CreateTeam {
            get {
                return ResourceManager.GetString("CreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t use any of the prohibited characters..
        /// </summary>
        internal static string DontUseProhibitedChars {
            get {
                return ResourceManager.GetString("DontUseProhibitedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error registering your user..
        /// </summary>
        internal static string ErrorRegisteringUser {
            get {
                return ResourceManager.GetString("ErrorRegisteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the necessary fields..
        /// </summary>
        internal static string FillNecessaryFields {
            get {
                return ResourceManager.GetString("FillNecessaryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brainstorming Finding Name.
        /// </summary>
        internal static string FindingName {
            get {
                return ResourceManager.GetString("FindingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea Description:.
        /// </summary>
        internal static string IdeaDescription {
            get {
                return ResourceManager.GetString("IdeaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how many ideas you want to have in one round.
        /// </summary>
        internal static string IdeasDescription {
            get {
                return ResourceManager.GetString("IdeasDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your insertion type.
        /// </summary>
        internal static string InsertSpecialTitle {
            get {
                return ResourceManager.GetString("InsertSpecialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a number of ideas between 0 and 100..
        /// </summary>
        internal static string InvalidNrOfIdeas {
            get {
                return ResourceManager.GetString("InvalidNrOfIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a round time between 0 and 100 minutes..
        /// </summary>
        internal static string InvalidRoundTime {
            get {
                return ResourceManager.GetString("InvalidRoundTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Team Members.
        /// </summary>
        internal static string InviteMembers {
            get {
                return ResourceManager.GetString("InviteMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have joined the team! Navigate back to the teamlist to see it..
        /// </summary>
        internal static string JoinedTeamMessage {
            get {
                return ResourceManager.GetString("JoinedTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined Team.
        /// </summary>
        internal static string JoinedTeamTitle {
            get {
                return ResourceManager.GetString("JoinedTeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Team.
        /// </summary>
        internal static string JoinTeam {
            get {
                return ResourceManager.GetString("JoinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Team.
        /// </summary>
        internal static string LeaveTeam {
            get {
                return ResourceManager.GetString("LeaveTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with your login, please try again..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Brainstorming.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} Members joined..
        /// </summary>
        internal static string MemberCountString {
            get {
                return ResourceManager.GetString("MemberCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method 635.
        /// </summary>
        internal static string Method635 {
            get {
                return ResourceManager.GetString("Method635", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Ideas.
        /// </summary>
        internal static string MoreIdeas {
            get {
                return ResourceManager.GetString("MoreIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Teams.
        /// </summary>
        internal static string MyTeams {
            get {
                return ResourceManager.GetString("MyTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names must be shorter than 22 characters and without spaces or periods..
        /// </summary>
        internal static string NameConstraints {
            get {
                return ResourceManager.GetString("NameConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no brainstorming findings for this team yet.. 
        ///Add a brainstorming finding below or wait until another team member creates one..
        /// </summary>
        internal static string NoFindingsYet {
            get {
                return ResourceManager.GetString("NoFindingsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t belong to a team yet.. 
        ///Join or add a team below.
        /// </summary>
        internal static string NoTeamYet {
            get {
                return ResourceManager.GetString("NoTeamYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Ideas.
        /// </summary>
        internal static string NrOfIdeas {
            get {
                return ResourceManager.GetString("NrOfIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Ideas, e.g. 3.
        /// </summary>
        internal static string NrOfIdeasPlaceholder {
            get {
                return ResourceManager.GetString("NrOfIdeasPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the passwords match..
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Idea.
        /// </summary>
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pattern has been added to the current wave. Navigate back to see it..
        /// </summary>
        internal static string PatternAddedMessage {
            get {
                return ResourceManager.GetString("PatternAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern added.
        /// </summary>
        internal static string PatternAddedTitle {
            get {
                return ResourceManager.GetString("PatternAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the code inside the area.
        /// </summary>
        internal static string PlaceQrInArea {
            get {
                return ResourceManager.GetString("PlaceQrInArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited characters (comma-separated, including whitespace): {0}.
        /// </summary>
        internal static string ProhibitedCharsText {
            get {
                return ResourceManager.GetString("ProhibitedCharsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose (optional).
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefly describe the purpose of your team.
        /// </summary>
        internal static string PurposeText {
            get {
                return ResourceManager.GetString("PurposeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more online....
        /// </summary>
        internal static string ReadMoreOnline {
            get {
                return ResourceManager.GetString("ReadMoreOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Time.
        /// </summary>
        internal static string RoundTime {
            get {
                return ResourceManager.GetString("RoundTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what your base round time will be. This will be incremented by 1 min every round.
        /// </summary>
        internal static string RoundTimeDescription {
            get {
                return ResourceManager.GetString("RoundTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Round Time in mins.
        /// </summary>
        internal static string RoundTimeText {
            get {
                return ResourceManager.GetString("RoundTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet {0} of {1}.
        /// </summary>
        internal static string SheetNrOfNr {
            get {
                return ResourceManager.GetString("SheetNrOfNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch Idea.
        /// </summary>
        internal static string Sketch {
            get {
                return ResourceManager.GetString("Sketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketching Page.
        /// </summary>
        internal static string SketchPage {
            get {
                return ResourceManager.GetString("SketchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sketch has been saved! Navigate back to the brainstorming to see it..
        /// </summary>
        internal static string SketchSavedMessage {
            get {
                return ResourceManager.GetString("SketchSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch Saved.
        /// </summary>
        internal static string SketchSavedTitle {
            get {
                return ResourceManager.GetString("SketchSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again..
        /// </summary>
        internal static string SomethingWrongTryAgain {
            get {
                return ResourceManager.GetString("SomethingWrongTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Brainstorming.
        /// </summary>
        internal static string StartBrainstorming {
            get {
                return ResourceManager.GetString("StartBrainstorming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the participants have joined. Navigate back to see the team..
        /// </summary>
        internal static string TeamFullMessage {
            get {
                return ResourceManager.GetString("TeamFullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Size.
        /// </summary>
        internal static string TeamSize {
            get {
                return ResourceManager.GetString("TeamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how many participants the team should have.
        /// </summary>
        internal static string TeamSizeDescription {
            get {
                return ResourceManager.GetString("TeamSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Participants.
        /// </summary>
        internal static string TeamSizeText {
            get {
                return ResourceManager.GetString("TeamSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your team members to scan the QR-Code to join the team.
        /// </summary>
        internal static string TellMembersToJoin {
            get {
                return ResourceManager.GetString("TellMembersToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use numbers in the corresponding fields..
        /// </summary>
        internal static string UseNumbersInFields {
            get {
                return ResourceManager.GetString("UseNumbersInFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re waiting for the brainstorming to get kicked off by the moderator. Here&apos;s some information about the brainstorming you&apos;re about to take part in:.
        /// </summary>
        internal static string WaitingForBrainstormingToStartMessage {
            get {
                return ResourceManager.GetString("WaitingForBrainstormingToStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Brainstorming to Start.
        /// </summary>
        internal static string WaitingForBrainstormingToStartTitle {
            get {
                return ResourceManager.GetString("WaitingForBrainstormingToStartTitle", resourceCulture);
            }
        }
    }
}
