//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Method635.App.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Method635.App.Forms.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Team, placing call to join it...
        /// </summary>
        internal static string BottomOverlayText {
            get {
                return ResourceManager.GetString("BottomOverlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brainstorming.
        /// </summary>
        internal static string Brainstorming {
            get {
                return ResourceManager.GetString("Brainstorming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brainstorming Findings.
        /// </summary>
        internal static string BrainstormingFindings {
            get {
                return ResourceManager.GetString("BrainstormingFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the icon to start Brainstorming..
        /// </summary>
        internal static string ClickToStartBrainstorming {
            get {
                return ResourceManager.GetString("ClickToStartBrainstorming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t use any of the prohibited characters..
        /// </summary>
        internal static string DontUseProhibitedChars {
            get {
                return ResourceManager.GetString("DontUseProhibitedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error registering your user..
        /// </summary>
        internal static string ErrorRegisteringUser {
            get {
                return ResourceManager.GetString("ErrorRegisteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the necessary fields..
        /// </summary>
        internal static string FillNecessaryFields {
            get {
                return ResourceManager.GetString("FillNecessaryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with your login, please try again..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} Members joined..
        /// </summary>
        internal static string MemberCountString {
            get {
                return ResourceManager.GetString("MemberCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Teams.
        /// </summary>
        internal static string MyTeams {
            get {
                return ResourceManager.GetString("MyTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the passwords match..
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited characters (comma-separated, including whitespace): {0}.
        /// </summary>
        internal static string ProhibitedCharsText {
            get {
                return ResourceManager.GetString("ProhibitedCharsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet {0} of {1}..
        /// </summary>
        internal static string SheetNrOfNr {
            get {
                return ResourceManager.GetString("SheetNrOfNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again..
        /// </summary>
        internal static string SomethingWrongTryAgain {
            get {
                return ResourceManager.GetString("SomethingWrongTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use numbers in the corresponding fields..
        /// </summary>
        internal static string UseNumbersInFields {
            get {
                return ResourceManager.GetString("UseNumbersInFields", resourceCulture);
            }
        }
    }
}
